# Generated by Django 6.0 on 2026-01-01 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('is_halal', models.BooleanField(default=True)),
                ('is_crypto', models.BooleanField(default=False)),
                ('min_stop_distance', models.DecimalField(decimal_places=6, default=0.0001, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TradeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('demo', 'Demo'), ('real', 'Real')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=20)),
                ('equity', models.DecimalField(decimal_places=2, max_digits=20)),
                ('max_risk_per_trade', models.FloatField(default=2.0)),
                ('max_daily_loss', models.FloatField(default=5.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('mode', models.CharField(choices=[('ULTRA', 'Ultra Calm'), ('SEMI', 'Semi Calm')], max_length=5)),
                ('entry_price', models.DecimalField(decimal_places=6, max_digits=20)),
                ('stop_loss', models.DecimalField(decimal_places=6, max_digits=20)),
                ('take_profit', models.DecimalField(decimal_places=6, max_digits=20)),
                ('risk_percent', models.FloatField()),
                ('position_size', models.DecimalField(decimal_places=4, max_digits=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.instrument')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='trading.tradeaccount')),
            ],
        ),
    ]
