# Generated by Django 4.2.7 on 2026-01-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='remaining_size',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='timeframe',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='position',
            name='unrealized_pnl',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('PARTIAL', 'Partial')], default='OPEN', max_length=10),
        ),
        migrations.AlterField(
            model_name='position',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True),
        ),
        migrations.AlterModelTable(
            name='instrument',
            table='trading_instrument',
        ),
        migrations.AlterModelTable(
            name='position',
            table='trading_position',
        ),
        migrations.AlterModelTable(
            name='tradeaccount',
            table='trading_tradeaccount',
        ),
    ]
