# Generated by Django 5.2.9 on 2026-01-18 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='instrument',
        ),
        migrations.RemoveField(
            model_name='position',
            name='account',
        ),
        migrations.RemoveField(
            model_name='tradeaccount',
            name='user',
        ),
        migrations.DeleteModel(
            name='Instrument',
        ),
        migrations.DeleteModel(
            name='Position',
        ),
        migrations.DeleteModel(
            name='TradeAccount',
        ),
    ]
