# Generated by Django 4.2.7 on 2026-01-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_position_remaining_size_position_timeframe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSE', 'CLOSE'), ('PARTIAL', 'PARTIAL'), ('SL_HIT', 'SL_HIT'), ('TP_HIT', 'TP_HIT'), ('MODIFIED', 'MODIFIED')], max_length=20)),
                ('price', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('size', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trading.position')),
            ],
            options={
                'db_table': 'trading_positionlog',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['position', '-created_at'], name='trading_pos_positio_09c597_idx'), models.Index(fields=['event_type'], name='trading_pos_event_t_34944b_idx')],
            },
        ),
    ]
