# Generated by Django 4.2.7 on 2026-01-19 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_positionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='hedge_disabled',
            field=models.BooleanField(default=True, help_text='If True, prevents opposite positions (hedging) for same instrument'),
        ),
    ]
