# Generated by Django 5.2.9 on 2026-01-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_remove_position_instrument_remove_position_account_and_more'),
        ('trading', '0004_position_hedge_disabled'),
    ]

    operations = [
    ]
