# Generated by Django 5.2.9 on 2026-01-23 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audit_type', models.CharField(choices=[('wallet_consistency', 'Wallet Consistency'), ('transaction_integrity', 'Transaction Integrity'), ('balance_verification', 'Balance Verification'), ('sharia_compliance', 'Sharia Compliance')], max_length=50)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=20)),
                ('account_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('account_number', models.CharField(blank=True, max_length=20)),
                ('is_consistent', models.BooleanField(default=True)),
                ('expected_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('actual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('difference', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('message', models.TextField()),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['audit_type', '-created_at'], name='audit_logs_audit_t_ed27e3_idx'), models.Index(fields=['severity', '-created_at'], name='audit_logs_severit_a4af98_idx'), models.Index(fields=['account_id', '-created_at'], name='audit_logs_account_0e7c33_idx'), models.Index(fields=['is_consistent', '-created_at'], name='audit_logs_is_cons_6ec69d_idx')],
            },
        ),
    ]
