# Generated by Django 5.2.9 on 2026-01-02 17:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('kyc_status', models.CharField(default='pending', max_length=20)),
                ('compliance_mode', models.CharField(choices=[('standard', 'STANDARD'), ('shariat_compliant', 'SHARIAT_COMPLIANT')], default='standard', max_length=20)),
                ('preferred_language', models.CharField(default='en', max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('demo', 'DEMO'), ('real', 'REAL')], max_length=10)),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('suspended', 'SUSPENDED'), ('closed', 'CLOSED'), ('pending_kyc', 'PENDING_KYC'), ('margin_call', 'MARGIN_CALL')], default='pending_kyc', max_length=20)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('equity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('max_daily_loss', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('daily_loss_current', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('daily_loss_reset_date', models.DateField(auto_now_add=True)),
                ('max_leverage', models.IntegerField(default=100)),
                ('is_shariat_compliant', models.BooleanField(default=False)),
                ('swap_free', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts',
                'unique_together': {('user', 'account_type')},
            },
        ),
        migrations.CreateModel(
            name='RiskLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_leverage', models.IntegerField(default=100)),
                ('max_daily_loss_amount', models.DecimalField(decimal_places=2, max_digits=18, null=True)),
                ('max_daily_loss_percent', models.DecimalField(decimal_places=2, default=Decimal('5.0'), max_digits=5)),
                ('max_position_size_percent', models.DecimalField(decimal_places=2, default=Decimal('20.0'), max_digits=5)),
                ('max_open_positions', models.IntegerField(default=10)),
                ('max_lot_size', models.DecimalField(decimal_places=2, default=Decimal('100.0'), max_digits=10)),
                ('max_overnight_exposure_percent', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('forbidden_instruments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_limits', to='accounts.account')),
            ],
            options={
                'db_table': 'risk_limits',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('deposit', 'DEPOSIT'), ('withdraw', 'WITHDRAW'), ('trade_lock', 'TRADE_LOCK'), ('trade_release', 'TRADE_RELEASE'), ('trade_pnl', 'TRADE_PNL'), ('fee', 'FEE'), ('commission', 'COMMISSION'), ('swap', 'SWAP'), ('bonus', 'BONUS'), ('refund', 'REFUND')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED'), ('rejected', 'REJECTED')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=18)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=18)),
                ('trade_id', models.UUIDField(blank=True, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
            ],
            options={
                'db_table': 'transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('visa', 'VISA'), ('mastercard', 'MASTERCARD'), ('crypto_btc', 'CRYPTO_BTC'), ('crypto_eth', 'CRYPTO_ETH'), ('crypto_usdt', 'CRYPTO_USDT'), ('crypto_usdc', 'CRYPTO_USDC'), ('bank_transfer', 'BANK_TRANSFER'), ('islamic_gateway', 'ISLAMIC_GATEWAY'), ('paypal', 'PAYPAL')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=200)),
                ('gateway_response', models.JSONField(default=dict)),
                ('crypto_address', models.CharField(blank=True, max_length=200)),
                ('crypto_txid', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED'), ('rejected', 'REJECTED')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='accounts.account')),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction')),
            ],
            options={
                'db_table': 'deposits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_deposits', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_withdrawals', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('total_fees_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='accounts.account')),
            ],
            options={
                'db_table': 'wallets',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method', models.CharField(choices=[('visa', 'VISA'), ('mastercard', 'MASTERCARD'), ('crypto_btc', 'CRYPTO_BTC'), ('crypto_eth', 'CRYPTO_ETH'), ('crypto_usdt', 'CRYPTO_USDT'), ('crypto_usdc', 'CRYPTO_USDC'), ('bank_transfer', 'BANK_TRANSFER'), ('islamic_gateway', 'ISLAMIC_GATEWAY'), ('paypal', 'PAYPAL')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=18)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('destination_address', models.CharField(max_length=200)),
                ('destination_details', models.JSONField(default=dict)),
                ('gateway_transaction_id', models.CharField(blank=True, max_length=200)),
                ('gateway_response', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('processing', 'PROCESSING'), ('completed', 'COMPLETED'), ('failed', 'FAILED'), ('cancelled', 'CANCELLED'), ('rejected', 'REJECTED')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='accounts.account')),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.transaction')),
            ],
            options={
                'db_table': 'withdrawals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', '-created_at'], name='transaction_account_5ef993_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['trade_id'], name='transaction_trade_i_b3aa2d_idx'),
        ),
    ]
