# Generated by Django 4.2.7 on 2026-01-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='compliance_mode',
            field=models.CharField(choices=[('standard', 'STANDARD'), ('shariat_compliant', 'SHARIAT_COMPLIANT'), ('ULTRA_CALM', 'ULTRA_CALM')], default='standard', max_length=20),
        ),
    ]
