# Generated by Django 5.2.9 on 2026-01-18 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_611c58_idx',
            old_name='notificatio_user_id_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_a4dd5c_idx',
            old_name='notificatio_user_id_is_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_account_581948_idx',
            old_name='notificatio_account_id_idx',
        ),
        migrations.AlterField(
            model_name='user',
            name='compliance_mode',
            field=models.CharField(choices=[('standard', 'STANDARD'), ('shariat_compliant', 'SHARIAT_COMPLIANT'), ('ULTRA_CALM', 'ULTRA_CALM')], default='standard', max_length=20),
        ),
    ]
