# Generated by Django 5.2.9 on 2026-01-23 12:29

import django.core.validators
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_notificatio_user_id_idx_notificatio_user_id_611c58_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_type', models.CharField(choices=[('lp_main', 'LP Main Account'), ('lp_reserve', 'LP Reserve Account'), ('lp_settlement', 'LP Settlement Account'), ('platform_revenue', 'Platform Revenue Account')], max_length=20)),
                ('account_number', models.CharField(db_index=True, max_length=20, unique=True)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('locked_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('lp_provider_name', models.CharField(blank=True, max_length=100)),
                ('lp_api_endpoint', models.URLField(blank=True)),
                ('lp_api_key', models.CharField(blank=True, max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_settlement_enabled', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'system_accounts',
            },
        ),
        migrations.AddField(
            model_name='account',
            name='freeze_reason',
            field=models.TextField(blank=True, help_text='Reason for account freeze'),
        ),
        migrations.AddField(
            model_name='account',
            name='frozen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='Account frozen due to Sharia compliance violation'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sharia_contract_type',
            field=models.CharField(blank=True, choices=[('vakala', 'VAKALA'), ('mudaraba', 'MUDARABA')], help_text='Sharia contract type (VAKALA or MUDARABA) for compliance validation', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='max_leverage',
            field=models.IntegerField(default=100, help_text='Maximum leverage ratio (1:max_leverage). Sharia limit: 1:500 (hard limit)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(500)]),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'account_type'], name='accounts_user_id_298889_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'status'], name='accounts_user_id_e05c06_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['account_type', 'status'], name='accounts_account_4a1d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['created_at'], name='accounts_created_1b6d37_idx'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['is_frozen', 'status'], name='accounts_is_froz_a74bf4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'status', '-created_at'], name='transaction_account_828ad7_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'status'], name='transaction_transac_9f5934_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_at'], name='transaction_created_5c02ac_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['sharia_contract_type'], name='transaction_sharia__8920ec_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'transaction_type', '-created_at'], name='transaction_account_c2e21f_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccount',
            index=models.Index(fields=['account_type'], name='system_acco_account_5099c4_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccount',
            index=models.Index(fields=['account_number'], name='system_acco_account_f933df_idx'),
        ),
        migrations.AddIndex(
            model_name='systemaccount',
            index=models.Index(fields=['is_active'], name='system_acco_is_acti_7cec5c_idx'),
        ),
    ]
