# Generated by Django 5.2.9 on 2026-01-28 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_compliance_mode'),
        ('accounts', '0004_systemaccount_account_freeze_reason_and_more'),
    ]

    operations = [
    ]
